# Generated by Django 3.1.4 on 2021-01-03 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_folder', '0002_auto_20210102_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_folder',
            name='owner',
        ),
        migrations.AddField(
            model_name='file_folder',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user'),
            preserve_default=False,
        ),
    ]
